mrs_uav_managers:

  estimation_manager:

    state_estimators: [
      "gps_baro",
      "ground_truth"
    ]

    initial_state_estimator: "gps_baro" # in simulation this keeps odom_main aligned with the simulator state
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)
